In [6]:
#Import packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
#load data
dataset = pd.read_csv('Companies_R&D_expense.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print(dataset.head())

   Training Expense  Innovation Lab Expense  Reward Expense    Profit
0          63408.86               129219.61        46085.25  97427.84
1          55493.95               103057.49       214634.81  96778.92
2          46426.07               157693.92       210797.67  96712.80
3          46014.02                85047.44       205517.64  96479.51
4          28663.76               127056.21       201126.82  90708.19


In [8]:
#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/5, random_state = 0)
print("X_train :",X_train)
print("X_test :",X_test)
print("y_train :",y_train)
print("y_test :",y_test)

X_train : [[114523.61 122616.84 261776.23]
 [ 94657.16 145077.58 282574.31]
 [120542.52 148718.95 311613.29]
 [ 78013.11 121597.55 264346.06]
 [165349.2  136897.8  471784.1 ]
 [ 38558.51  82982.09 174999.3 ]
 [  1315.46 115816.21 297114.46]
 [ 72107.6  127864.55 353183.81]
 [ 61994.48 115641.28  91131.24]
 [100671.96  91790.61 249744.55]
 [     0.   135426.92      0.  ]
 [ 93863.75 127320.38 249839.44]
 [119943.24 156547.42 256512.92]
 [   542.05  51743.15      0.  ]
 [ 77044.01  99281.34 140574.81]
 [153441.51 101145.55 407934.54]
 [ 64664.71 139553.16 137962.62]
 [ 28754.33 118546.05 172795.67]
 [  1000.23 124153.04   1903.93]
 [130298.13 145530.06 323876.68]
 [ 44069.95  51283.14 197029.42]
 [     0.   116983.8   45173.06]
 [ 73994.56 122782.75 303319.26]
 [ 61136.38 152701.92  88218.23]
 [ 55493.95 103057.49 214634.81]
 [ 22177.74 154806.14  28334.72]
 [ 86419.7  153514.11      0.  ]
 [134615.46 147198.87 127716.82]
 [ 20229.59  65947.93 185265.1 ]
 [131876.9   99814.71 362861.36]


In [9]:
#Train model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
#do prediction
pred_result = model.predict(X_test)
print("Predicted profit :",pred_result)

Predicted profit : [135959.98280965  57666.79131858  68883.03777226 108637.05124764
  85424.19726442 155781.75288658 115377.63750649 126378.43977498
 174073.93075243  72180.12374441]
